name: ThermoMPNN-D
channels:
  - bioconda
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch=*=*cuda*
  - pytorch-cuda=11.7
  - torchvision=*=*cu*
  - torchaudio=*=*cu*
  - torchmetrics
  - pytorch-lightning
  - biopython
  - wandb
  - mmseqs2
  - tqdm
  - pandas
  - numpy=1.26.4
  - omegaconf
  - python==3.10
  - joblib
  - cudatoolkit=11.7
  - scipy
  - scikit-learn
  - ipykernel
  - notebook
  